#! /bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config ~/.config/bspwm/picom/picom.conf & 
~/.config/bspwm/polybar/launch.sh &
feh --bg-fill ~/.config/bspwm/wallpapers/garuda/Golden\ Eagle.png &
dunst -config ~/.config/bspwm/dunst/dunstrc & 
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
